### ISSUE TITLE
Typos in README

### ISSUE THREAD

**Issue by jesse-stew** [dawndelatte/tiy_assignments#1]
Typos in the day four line of your README file.

**Comment by jesse-stew** [comment]
(Styles Conference)

**Comment by dawndelatte** [comment]
Thanks! All fixed now.

**Comment by jesse-stew** [comment]
Should "competed" be "completed"? Same line as typo above.

**Comment by dawndelatte** [comment]
Ah! Yes it should, I'll get that one now. Thanks!
