### ISSUE TITLE
Restaurant Style Tile Feedback 

### ISSUE THREAD

**Issue by samkap** [dawndelatte/tiy_assignments#10]
sooooo my browser just lost everything i wrote for you.
## v1

great colors, the condensed font (alt gothic) might be too condensed for body copy. Is there a not condensed option? . The button doesn't feel appropriate to this concept. It, to me, reminds me of 90s design, and not modern (with a lowercase m, so contemporary). I think more hierarchy in type sizes and weights could be introduced. Great solution on the two column wine list.
## v2

This gets the feel you were hoping for (i think) with picnicky vibes, but the handwritten font is humanistic but doesn't feel like with the summery, picnicky feel.
## v3

Spelling of polaroid. Colors feel approachable, warm, and pizza/beer like. I'd be curious to see the type of two (handwritten) on this one, it might read well with the polaroids. The two columns on the wine selection could work really well here as well, because I think seeing price comparisons aligned really lets the viewer/customer compare prices easily.

**Comment by dawndelatte** [comment]
Thanks for the feedback! I made second versions of these, just so I can compare the changes. 

v1 - I changed the header fonts to "Tablet Gothic Semi Condensed Heavy/Extra Bold" to explore better hierarchy between those. I also changed the body text from alt goth condensed on both versions to Facit regular and bold so it's more readable. I think you made this issue before I changed the button. I got similar feedback from Xinyu on it, so I made the color more inviting and rounded the corners.

v2 - I did a second version on this one with a new header font : FF Kava Pro Regular and Bold. 

v3 - I fixed polaroid, and made a second version using the Amatic SC google font (screen shot from typecast) to see how that looks together. I also separated the wine and prices into two columns, and I agree that looks much better.
