### ISSUE TITLE
Surf and Paddle logo

### ISSUE THREAD

**Issue by samkap** [dawndelatte/tiy_assignments#5]
theres a tiny issue of placement on the surf and paddle header for the logo and the logo text:
![screenshot 2015-02-09 08 02 29](https://cloud.githubusercontent.com/assets/2152574/6107626/180e3d60-b032-11e4-8aac-c1a629ceb63f.png)

**Comment by dawndelatte** [comment]
Brandon mentioned this as well and I'm wondering if it's a difference in screen size? It's lining up correct on my screen but I think the issue is that I used an absolute position on this. I will fix it today. Thanks!
