### ISSUE TITLE
style tiles

### ISSUE THREAD

**Issue by xinyu0** [dawndelatte/tiy_assignments#9]
V1
This one is my favorite. The color palette is very fun and interesting. I think it works very well for abgb. The chalkboard idea is great. There is enough contrast between the white and dark grey. I'm not so sure about the button. It doesn't feel causal and relax.  

V2
I really like the idea. I think it might only work on Jul 4th. Everything looks really nice together. 

V3
I like the fonts on "beer + food" but the green color on it I don't associate with beer or retro. The "beer+food" looks very manly but the menu items look a lit more girly.

**Comment by dawndelatte** [comment]
Thanks for the feedback! 
For v1, I changed the button to make it more inviting by rounding the corners and making it a brighter blue color.

For v2, I changed the red to a darker orange so it wouldn't have that obvious red white and blue "4th of July" vibe.

For v3, I changed the font to match the paragraph text (Lexia) and used heavier weights for the different headers. I also lightened the green and gave the colors a warmer, subtler vibe.
